### ISSUE TITLE
getAudioSessionId

### ISSUE THREAD

**Issue by karnadii** [danielR2001/flutter_exoplayer#1]
support for getAudioSessionId to implement this https://github.com/iamSahdeep/FlutterVisualizers?

**Comment by danielR2001** [comment]
Okay I will implement this feature as a stream.

**Comment by karnadii** [comment]
thanks

**Comment by danielR2001** [comment]
I've added this feature in the last commit, for now, I'm not updating the package for some reasons so just depend on the repository.

**Comment by karnadii** [comment]
got it, thanks anyway :D

Pada tanggal Min, 4 Agt 2019 21.03, Daniel <notifications@github.com>
menulis:
