### ISSUE TITLE
Update notification adhoc?

### ISSUE THREAD

**Issue by MagnusJohansson** [danielR2001/flutter_exoplayer#13]
I was looking through the code, but cannot find a way to update the Notification dynamically.
This would be useful for looking up cover art, and/or update title/artist on the fly.

Is it possible to update the Notification metadata dynamically (while the player is playing)?

**Comment by danielR2001** [comment]
It is possible to update the notification while the player playing by simply adding an update method that would update the notification, but I hadn't the time to develop this feature If you have the time for it you are more than welcome to submit a PR.

**Comment by husmen73** [comment]
It will be super with this method.

**Comment by danielR2001** [comment]
what do you prefer?

**Comment by danielR2001** [comment]
Hi, @husmen73 and @MagnusJohansson could you depend on my last committed version where I've added the new feature of updating Notification metadata dynamically and test it.
