### ISSUE TITLE
No Such Method 'play'

### ISSUE THREAD

**Issue by johnny-stevie** [danielR2001/flutter_exoplayer#15]
when I run this code:
`Future<void> play(String localFiles) async {
     await _player.play(
        "https://www.bensound.org/bensound-music/bensound-onceagain.mp3"
      );
}`

I get this error:

`Tried calling: play("https://www.bensound.org/bensound-music/bensound-onceagain.mp3")
E/flutter ( 7512): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 7512): #1      QuickSongAudioPlayer.play (package:quick_song/audio_player.dart:101:21)
E/flutter ( 7512): <asynchronous suspension>
E/flutter ( 7512): #2      _HomePageState.build.<anonymous closure>.<anonymous closure> (package:quick_song/home_widget.dart:134:46)
E/flutter ( 7512): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter ( 7512): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter ( 7512): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7512): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 7512): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter ( 7512): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 7512): #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 7512): #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7512): #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7512): #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7512): #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7512): #14     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 7512): #15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7512): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7512): #17     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 7512): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter ( 7512): `

Any help appreciated

**Comment by danielR2001** [comment]
I will look at it when I will have the time. Thanks for pointing out the issue.

**Comment by johnny-stevie** [comment]
Sorry, my bad, the bug was because the method i was using to call the exoplayer play method was private so wasn't callable.
I've come across another bug where when i play one file and then another simultaneously, the player doesnt respond to me when I call the .stop() method.

**Comment by danielR2001** [comment]
Ok, I need some more details for recreation, both are in BACKGROUND mode? It will be better if you send me the code that causes the bug.

**Comment by johnny-stevie** [comment]
Sorry, my fault. The reason why it didn't work was because _player var was private and couldn't be accessed from another class which is what I was doing.

**Comment by johnny-stevie** [comment]
@danielR2001 However I have stumbled across another problem, if you wouldn't mind looking at it, I am using flutter_downloader in conjunction with flutter_exoplayer and for some reason exoplayer is being called while the app launches so I receive the error 
`
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
E/AndroidRuntime(27814):        at danielr2001.audioplayer.AudioPlayerPlugin.<init>(AudioPlayerPlugin.java:94)
E/AndroidRuntime(27814):        at danielr2001.audioplayer.AudioPlayerPlugin.registerWith(AudioPlayerPlugin.java:88)
E/AndroidRuntime(27814):        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
E/AndroidRuntime(27814):        at com.johnwall.quick_song.DemoApplication.registerWith(DemoApplication.kt:11)
E/AndroidRuntime(27814):        at vn.hunghd.flutterdownloader.DownloadWorker.startBackgroundIsolate(DownloadWorker.java:124)
E/AndroidRuntime(27814):        at vn.hunghd.flutterdownloader.DownloadWorker.access$000(DownloadWorker.java:59)
E/AndroidRuntime(27814):        at vn.hunghd.flutterdownloader.DownloadWorker$1.run(DownloadWorker.java:97)
E/AndroidRuntime(27814):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(27814):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(27814):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(27814):        at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(27814):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27814):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(27814):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
`
