### ISSUE TITLE
Some features and questions

### ISSUE THREAD

**Issue by mohammadne** [danielR2001/flutter_exoplayer#17]
Thanks Daniel for your nice work .
the notification area is very awesome .
also I have some questions.
1 - can we controll it with headphone ?
2 - if other apps play audio , does it pause the song for example handle phone call interruptions ?
3 - does it support ios completely ?
4 - does it support lock screen controls ?

**Comment by danielR2001** [comment]
1 - Still working on it.
2. Yes, its called audio focus.
3. It doesn't support IOS as for now (i don't know objective C).
4. Yes, it has the notification control.
