### ISSUE TITLE
seekIndex fails silently without error message

### ISSUE THREAD

**Issue by johnny-stevie** [danielR2001/flutter_exoplayer#18]
When I call seekIndex,after a playlist has been loaded into the AudioPlayer, the seekIndex function fails silently without error message.
`
try{
    seekIndex(index);
     }on ErrorHint catch(e){
     player.seekIndex(index);
     }finally{
        play(localSongsPlaylist);
     }
`
Is there a reason why it always skips the try clause?
Any help appreciated.

**Comment by danielR2001** [comment]
Hi Johnny, first of all, to play playlist you need to call playAll() method, second of all, to seek specific index in the playlist before the player has started playing you need to just pass the index of the song you want to start with to the playAll method.

**Comment by danielR2001** [comment]
`      final Result result = await _audioPlayer.playAll(
        urls,
        index: 1,
        audioNotifications: audioNotifications,
      );`
