### ISSUE TITLE
Null when getURL() invoked

### ISSUE THREAD

**Issue by ArvinCS** [danielR2001/flutter_exoplayer#19]
> java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String danielr2001.audioplayer.models.AudioObject.getUrl()' on a null object reference
> E/AndroidRuntime(13097): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.initExoPlayer(ForegroundAudioPlayer.java:215)
> E/AndroidRuntime(13097): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.play(ForegroundAudioPlayer.java:238)

That's the error that show up everytime i want to play a song, thank you!
It's foreground mode

**Comment by danielR2001** [comment]
Hi, could you attach the code causing this error?

**Comment by ArvinCS** [comment]
`void _play() async {
    await widget.music.getAudioURL().then(
      (String url) {
        AudioNotification audioNotif = AudioNotification(
          smallIconFileName: "ic_launcher",
          title: widget.music.title,
          subTitle: "by ${widget.music.artist.toString()}",
          largeIconUrl: widget.music.thumbnail,
          isLocal: widget.music.isOffline(),
          notificationDefaultActions: NotificationDefaultActions.ALL,
        );
        debugPrint("player: ${getMPlayer().toString()}");
        debugPrint("notif: ${audioNotif.toString()}");
        debugPrint("url: ${url.toString()}");
        getMPlayer().play(url.toString(), respectAudioFocus: true, playerMode: PlayerMode.FOREGROUND, audioNotification: audioNotif, repeatMode: repeat, position: Duration(milliseconds: 0));
        setCurrentMusic(widget.music);
      }
    );
    setState(() => _playerState = PlayerState.PLAYING);
  }`
Sorry, there was no log about my code that causing that error, only code from yours.
But maybe this can help you :D

**Comment by danielR2001** [comment]
you can enable log with this line:  `AudioPlayer.logEnabled = true;`

**Comment by danielR2001** [comment]
also what version are you using?

**Comment by ArvinCS** [comment]
Tried it and the log showed nothing, I'm using lastest version

**Comment by ArvinCS** [comment]
Sometimes the player work with no error, but sometimes it errors

**Comment by ArvinCS** [comment]
I found what causing that error, it's onAudioSessionIdChange event.
Everytime i listen to that stream, it always crashed when i wanna play a music.
Good luck!

**Comment by ArvinCS** [comment]
Wait, I'm not sure about it.

**Comment by ArvinCS** [comment]
> E/AndroidRuntime(20423): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String danielr2001.audioplayer.models.AudioObject.getUrl()' on a null object reference
E/AndroidRuntime(20423): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.initExoPlayer(ForegroundAudioPlayer.java:215)
E/AndroidRuntime(20423): 	at danielr2001.audioplayer.audioplayers.ForegroundAudioPlayer.play(ForegroundAudioPlayer.java:238)
E/AndroidRuntime(20423): 	at danielr2001.audioplayer.AudioPlayerPlugin$1.onServiceConnected(AudioPlayerPlugin.java:75)
E/AndroidRuntime(20423): 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1652)
E/AndroidRuntime(20423): 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1681)
E/AndroidRuntime(20423): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(20423): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20423): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(20423): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(20423): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20423): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(20423): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by danielR2001** [comment]
As I can see from the logs the player crushes because the JAVA AudioObject is not being created properly for some reason, I will look at it in the evening or tomorrow. Thanks for pointing out the bug.

**Comment by ArvinCS** [comment]
Good luck! Hope you fix it asap.

**Comment by ArvinCS** [comment]
Any news?

**Comment by ArvinCS** [comment]
Hi, so you dont have time to fix it? I need your plugin to continue my project tbh

**Comment by danielR2001** [comment]
Sorry, I have a very busy schedule in the last past weeks. If you know JAVA you are more than welcome to try and fix the issue.

**Comment by ArvinCS** [comment]
I'm trying to fix the issue, but I'm not sure i can fix it because it doesn't show any error log since i upgraded my flutter to lastest. It makes me hard to find the bug. But i will do my best :)

**Comment by danielR2001** [comment]
Thanks! I really appreciate your help!
