### ISSUE TITLE
MediaNotification custom event/method

### ISSUE THREAD

**Issue by karnadii** [danielR2001/flutter_exoplayer#2]
Can we have the button on notification have custom event? I want the user to select what to play, so I can't use playAll() method to enable next prev. 
my method is something like this
```dart
 play(index) async {
    final Result result = await exoPlayer.play(
      radioList[index].streamUrl,
      repeatMode: true,
      respectAudioFocus: false,
      playerMode: PlayerMode.FOREGROUND,
      audioNotification: AudioNotification(        
            smallIconFileName: "ic_launcher",
            title: radioList[index].title,
            subTitle: "RADIOSUKA",
            largeIconUrl: radioList[index].logo,
            isLocal: false,
            notificationMode: NotificationMode.BOTH),
    );
    if (result == Result.error) {
      print("something went wrong in play method :(");
    }
  }

  playNext() {
    ++currentIndex;
    if (isPlaying) stop();
    play(currentIndex);
  }

  playPrev() {
    if (isPlaying) stop();
    --currentIndex;
    play(currentIndex);
  }

```
thanks

**Comment by danielR2001** [comment]
Yes I have found a solution for this, I will add an additional parameter to audioNotification object - NotificationActionCallbackMode enum with two options: 1.defaut 2.custom, the default will act as now, but the custom will send a stream with the action pressed on the notification (so you would have kind of a callback with the stream)

**Comment by karnadii** [comment]
why are you closing this? are you won't add this feature in the near future?
