### ISSUE TITLE
does this package support ios like audioplayers ?

### ISSUE THREAD

**Issue by mohammadne** [danielR2001/flutter_exoplayer#21]
I don't have mac to test it .
but if I use your package for ios , does it crash ?
because you write ```for now works only for Android.```
or it workes correctly without notification controll ?

**Comment by danielR2001** [comment]
Hi, The package doesn't support IOS at all :( 
but if you know Objective C and could help implement IOS support you are more then welcome to do it :D

**Comment by danielR2001** [comment]
and I don't think the app will crash on IOS (I don't have IOS emulator).
