### ISSUE TITLE
AudioPlayer accessed from different pages

### ISSUE THREAD

**Issue by johnny-stevie** [danielR2001/flutter_exoplayer#24]
Hi @danielR2001 , this is a great plugin you made, it works perfectly. However, I was thinking if the following problem was solvable:
I have an AudioPlayer() object initialized in my Home class to play some audio files but I don't want to dispose of it and create another one when I go to another page (Favourites) to play a different set of audio files because I want to let the user to return to the home page the way they left it. I tried creating another AudioPlayer object in the Favourites page but it gives me this error which doesn't go away when i call the release or dispose method on the Home page AudioPlayer object,
`E/AudioPlayer:Can't start more than 1 service at a time, to stop service call release method`

Therefore, is it possible to access the same AudioPlayer() object from a different part of my app and play a different set of songs? Do I have to somehow make the AudioPlayer() global?

Any help is very much appreciated.

**Comment by danielR2001** [comment]
I think the best way to deal with the AudioPlayer object is to create a helper class in which you will create one instance of AudioPlayer, and only in that class, you will use this instance. I have one repository "my-music" - that is like Spotify app that has a helper class as I described.

**Comment by danielR2001** [comment]
I recommend you to use the helper class because you use a Foreground service and only one service can be activated at once so you need to have only one instance of AudioPlayer.

**Comment by johnny-stevie** [comment]
Thanks for the quick reply. I see that you used GetIt, does this keep the instance of AudioPlayer alive? If so, do you have to register it as a lazy singleton or a factory?

**Comment by danielR2001** [comment]
I m not expert in this area (This was my first time using singletons and factories) but I think you need to use the lazy singleton instead of the factory because you need only one and only instance of the AudioPlayer and not creating the AudioPlayer again and again (this will not work well with the Foreground service).

**Comment by johnny-stevie** [comment]
I tried it out. It works, thanks!

**Comment by SimonPeter1909** [comment]
@johnny-stevie Can u help me in global AudioPlayer()? I have used scoped model... and its working fine on all pages but my problem, when I close my app and reopen the app, the whole app restarts and AudioPlayer goes null but the audio is playing in the background. So I can't either stop background music or play new music. Please Help Me @danielR2001 and johnny-stevie...

**Comment by johnny-stevie** [comment]
Have u installed get_it in your pubspec.yaml package?

**Comment by SimonPeter1909** [comment]
@johnny-stevie no... Do I have to replace scoped_model with get_it?

**Comment by danielR2001** [comment]
Hi @SimonPeter1909 I didn't use the scoped model yet so I can't answer really answer you properly whats your problem is but I think you need to try and use get_it and check if it works for you (for me it did perfectly in my [my-music](https://github.com/danielR2001/my-music) app).
