### ISSUE TITLE
Back button stops audio player

### ISSUE THREAD

**Issue by wisecoders** [danielR2001/flutter_exoplayer#28]
Thanks for all the hard work. After start playing audio player, hitting back button closes the music. How can make it to run in the background?

**Comment by danielR2001** [comment]
Hi @wisecoders, as far as I understand you used BACKGROUND mode but you need the FOREGROUND mode so your music will play as foreground service and will not be killed.

**Comment by wisecoders** [comment]
I am using foreground mode. Say when user clicks plays a track and hits back button, audio playing stops.

**Comment by danielR2001** [comment]
It's very strange and not supposed to happen. The back button is as close the app?

**Comment by SimonPeter1909** [comment]
@wisecoders _audioplayer.dispose(); in the dispose() method makes the audio playing stop. Comment the dispose method and give a try...

**Comment by wisecoders** [comment]
@danielR2001  Thanks for the feedback. @SimonPeter1909  solution worked for me.

just one more question though.  Once I have dismissed the player from the notification, I am not able to play anything from the application again. It says "you tried to call audio conrolling methods on released audio player :("  how to reinitialize the audio player again?

**Comment by samir1005** [comment]
> 
> 
> @danielR2001 Thanks for the feedback. @SimonPeter1909 solution worked for me.
> 
> just one more question though. Once I have dismissed the player from the notification, I am not able to play anything from the application again. It says "you tried to call audio conrolling methods on released audio player :(" how to reinitialize the audio player again?

you have a solution please?

**Comment by Bassaid** [comment]
> @danielR2001 Thanks for the feedback. @SimonPeter1909 solution worked for me.
> 
> just one more question though. Once I have dismissed the player from the notification, I am not able to play anything from the application again. It says "you tried to call audio conrolling methods on released audio player :(" how to reinitialize the audio player again?

I have the same problem
And I did not find a solution, you have a solution please?
