### ISSUE TITLE
Foreground

### ISSUE THREAD

**Issue by gladiator2b** [danielR2001/flutter_exoplayer#3]
hello how to put in the foreground if we click on sample 1.
I would like to have only one button

**Comment by danielR2001** [comment]
I didn't understand your question, but to start the foreground service you need to pass player mode parameter as PlayerMode.FOREGROUND in the audioplayer.play() method. And also if you pass the the foreground parameter you need to also pass the AudioObject or a list of AudioObjects if playing playlist.

**Comment by gladiator2b** [comment]
what i mean is: how to highlight sample 1 instead of sample 4

**Comment by gladiator2b** [comment]
currently the foreground works if we click on the sample 4 me I would do it for any button

**Comment by danielR2001** [comment]
You need to do as I already said before, just pass the player mode as foreground in the _play() function in player_widget class.

**Comment by gladiator2b** [comment]
hi,
if I put the foreground like this the buttons do not work  Future<void> _play() async {
    if (url != null) {
      final Result result = await _audioPlayer.play(
        url,
        repeatMode: true,
        respectAudioFocus: false,
        playerMode: PlayerMode.FOREGROUND,
      );

anymore
more if I put that it does not work either
audioNotifications: audioNotifications, 
final Result result = await audioPlayer.  play (url,
       repeatMode : true ,
       respectAudioFocus : true ,
       playerMode : PlayerMode .  FOREGROUND ,
       audioObject : audioObject);
   if (result == Result . ERROR ) {
     print ( "something went wrong in play method :(" );
   }
