### ISSUE TITLE
The app stops crash

### ISSUE THREAD

**Issue by dimiril** [danielR2001/flutter_exoplayer#33]
The app stops when running

_audioPlayer.playAll()

**Comment by danielR2001** [comment]
need more info than that...

**Comment by dimiril** [comment]
hello how load list from api to
List<String> urls = [
     
    ];

**Comment by dimiril** [comment]
'package:flutter/src/material/slider.dart': Failed assertion: line 132 pos 15: 'value >= min && value <= max': is not true.

**Comment by danielR2001** [comment]
Oh yes that's an error caused by the position/duration being null when playback starts, it minor error in the app itself not the library.
