### ISSUE TITLE
Not showing notification service

### ISSUE THREAD

**Issue by nekomaruh** [danielR2001/flutter_exoplayer#34]
The app is not showing the notification service, it's just working when playing local & remote files in third tabbar option.

**Comment by danielR2001** [comment]
is it still happening with version 0.6.1?

**Comment by nekomaruh** [comment]
I don't know actually, i have posted this 1 year ago and migrated to native Code.

**Comment by danielR2001** [comment]
ok, so I'm closing this issue. if this issue will happen in 0.6.1+ you can open a new issue. thanks
