### ISSUE TITLE
is there a way to loop through an audio?

### ISSUE THREAD

**Issue by hewa-jalal** [danielR2001/flutter_exoplayer#37]

**Comment by danielR2001** [comment]
Yes, set the repeat mode to true.

**Comment by hewa-jalal** [comment]
thanks, and is there a plan to add an gape-less audio loop, also playing from assets will be great.

**Comment by danielR2001** [comment]
it is gape less in playlist mode. but it's not crossfading like Spotify if that's what you mean? and playing from assets is a bit tricky.

**Comment by hewa-jalal** [comment]
okay great, i hope assets be added in the future, good luck.
