### ISSUE TITLE
One AudioPlayer instance can play multiple audio files (readme says otherwise)

### ISSUE THREAD

**Issue by lstimac** [danielR2001/flutter_exoplayer#39]
Hi, I have a problem with my AudioPlayer instance being able to play multiple sound files simultaneously. Plugin docs say the following:

> An **AudioPlayer instance can play a single audio at a time**. To create it, simply call the constructor:
> 
>   AudioPlayer audioPlayer = AudioPlayer();

> You can create multiple instances to play audio simultaneously, but only if you choose playerMode: PlayerMode.BACKGROUND, because android can't run two similar services.

<br>
I tried playing a song on an instance that is already playing, and instead of stopping the current song and starting another it keeps playing and just starts another one. Is this a bug? Shouldn't one instance stop the current playback and start another one, and if I want simultaneous playback I use a second instance?

**Comment by danielR2001** [comment]
yes sir, that was a bug that I fixed now. thank you for pointing this out. :D
