### ISSUE TITLE
Notification with a single audio

### ISSUE THREAD

**Issue by romaque** [danielR2001/flutter_exoplayer#44]
Hi

How do I use notification with a single audio

I'm doing it this way but don't display the notification and Android kills the audio

AudioNotification audioObject = AudioNotification(
      smallIconFileName: "ic_launcher",
      title: "Live",
      subTitle: "Live running",
      isLocal: false,
      notificationDefaultActions: NotificationDefaultActions.ALL,
      notificationCustomActions: NotificationCustomActions.TWO,
);

AudioPlayer _audioPlayer = AudioPlayer();

final Result result = await _audioPlayer.play(
      "http://stm.painelfoxcasthd.online:7102/;",
      repeatMode: true,
      respectAudioFocus: true,
      audioNotification: audioObject,
      playerMode: PlayerMode.FOREGROUND,
);

**Comment by spy-reality** [comment]
Try this method

smallIconFileName: "mipmap/ic_launcher",
