### ISSUE TITLE
Notification Customization

### ISSUE THREAD

**Issue by emme10** [danielR2001/flutter_exoplayer#5]
Hi I would like to ask if its possible to implement the following customizations.

 - [ ]   A way to show the current progress of the audio in the notification or hide the progressbar and show a text with the current time. 
- [x]  A way to show seekPosition buttons to skip for example 5 seconds in the notification. 
- [x]  Customize the Icons for example outline icons or fontawesome icons etc.
- [x] Dismiss the notification if the audio was stopped with `_audioPlayer.stop()`
      It is dismissed but restarts after some milliseconds and displays the notification again and if I try to play again it crashes because the player was released after the stop methode. 
- [ ] A way to decide between expanded or collapsed notification style if possible.
- [ ] If subtitle is empty -> show the title centered vertical on the collapsed notification

**Comment by danielR2001** [comment]
Hi, I'm a little busy right now, but I will try to fix/implement all of what you mentioned. If you know JAVA you are welcome to submit a PR.

**Comment by danielR2001** [comment]
Hi I wont add the skip buttons, but i will set the option to add two more buttons as you wish (fully customizable).

**Comment by emme10** [comment]
awesome thank you.

**Comment by danielR2001** [comment]
Hi in the new version (0.5.0) there is an option to add two fully custom actions, the instructions are in README.md. Enjoy! :D

**Comment by emme10** [comment]
Hi, thank you very much. I will check it out :D

**Comment by danielR2001** [comment]
I'm still working on the audio. stop notification won't dismiss. Hope to fix it soon.

**Comment by danielR2001** [comment]
If you know java and dart i would love some help in the library :D

**Comment by emme10** [comment]
There's no hurry for that as long as it is fixed in the future. The release of my app is planned for Spring 2020 so there should be enough time to fix and improve.  
I would love to help but unfortunately I have a lot of ongoing projects for the company I work for.
Maybe in the future when most of the other projects are done :)

**Comment by danielR2001** [comment]
Enjoy version 0.5.1 all your bugs/enchancments are fixed!

**Comment by getmmg** [comment]
Is there a way to hide the progress bar in notification ?
